Add nvcomp support to older CUDA 11 versions on aarch64. (#255)
Nightly CI runs are failing for CUDA 11.4 on ARM because the `cudatoolkit` package list does not specify a matrix entry for CUDA 11.4 on ARM for `nvcomp`. This adds the missing matrix entries for supported CUDA 11 versions.

See failure below:
```
ValueError: No matching matrix found in 'cudatoolkit' for: {'cuda': '11.4', 'arch': 'aarch64'}
```

https://github.com/rapidsai/kvikio/actions/runs/5652999609/job/15313480885

Authors:
  - Bradley Dice (https://github.com/bdice)

Approvers:
  - Vyas Ramasubramani (https://github.com/vyasr)

URL: https://github.com/rapidsai/kvikio/pull/255