Fix missing-field-initializers build failure in kvikio_nic nsys plugin (#1068)
Attempt at fixing the nightly [velox-cudf](https://github.com/NVIDIA/cudf/actions/runs/34568181965/job/103164498430#step:9:1676) build job

<details>

```
FAILED: _deps/kvikio-build/nsys_plugins/nic/CMakeFiles/kvikio_nic_nsys_plugin.dir/kvikio_nic_nsys_plugin.cpp.o 
sccache /opt/rh/gcc-toolset-14/root/usr/bin/g++ -DVELOX_ENABLE_PARQUET -I/__w/cudf/cudf/_build/release/_deps/nvtx3-src/c/include -mavx2 -mfma -mavx -mf16c -mlzcnt -mbmi2 -DUSE_VELOX_COMMON_BASE -DHAS_UNCAUGHT_EXCEPTIONS -Wall -Wextra -Wno-unused        -Wno-unused-parameter        -Wno-sign-compare        -Wno-ignored-qualifiers        -Wno-implicit-fallthrough          -Wno-class-memaccess          -Wno-comment          -Wno-int-in-bool-context          -Wno-redundant-move          -Wno-array-bounds          -Wno-maybe-uninitialized          -Wno-unused-result          -Wno-format-overflow          -Wno-strict-aliasing -Wno-error=template-id-cdtor -Wno-overloaded-virtual -Wno-error=tautological-compare -O3 -DNDEBUG -std=gnu++20 -fPIE -fdiagnostics-color=always -Wall -Werror -Wno-unknown-pragmas -MD -MT _deps/kvikio-build/nsys_plugins/nic/CMakeFiles/kvikio_nic_nsys_plugin.dir/kvikio_nic_nsys_plugin.cpp.o -MF _deps/kvikio-build/nsys_plugins/nic/CMakeFiles/kvikio_nic_nsys_plugin.dir/kvikio_nic_nsys_plugin.cpp.o.d -o _deps/kvikio-build/nsys_plugins/nic/CMakeFiles/kvikio_nic_nsys_plugin.dir/kvikio_nic_nsys_plugin.cpp.o -c /__w/cudf/cudf/_build/release/_deps/kvikio-src/cpp/nsys_plugins/nic/kvikio_nic_nsys_plugin.cpp
/__w/cudf/cudf/_build/release/_deps/kvikio-src/cpp/nsys_plugins/nic/kvikio_nic_nsys_plugin.cpp:76:1: error: missing initializer for member 'nvtxSemanticsCounter_v1::min' [-Werror=missing-field-initializers]
   76 | };
      | ^
/__w/cudf/cudf/_build/release/_deps/kvikio-src/cpp/nsys_plugins/nic/kvikio_nic_nsys_plugin.cpp:76:1: error: missing initializer for member 'nvtxSemanticsCounter_v1::max' [-Werror=missing-field-initializers]
/__w/cudf/cudf/_build/release/_deps/kvikio-src/cpp/nsys_plugins/nic/kvikio_nic_nsys_plugin.cpp: In function 'uint64_t {anonymous}::register_rate_schema(nvtxDomainHandle_t)':
/__w/cudf/cudf/_build/release/_deps/kvikio-src/cpp/nsys_plugins/nic/kvikio_nic_nsys_plugin.cpp:262:66: error: missing initializer for member 'nvtxPayloadSchemaEntry_v1::flags' [-Werror=missing-field-initializers]
  262 |                              .offset      = offsetof(NicRates, rx)},
      |                                                                  ^
/__w/cudf/cudf/_build/release/_deps/kvikio-src/cpp/nsys_plugins/nic/kvikio_nic_nsys_plugin.cpp:262:66: error: missing initializer for member 'nvtxPayloadSchemaEntry_v1::arrayOrUnionDetail' [-Werror=missing-field-initializers]
/__w/cudf/cudf/_build/release/_deps/kvikio-src/cpp/nsys_plugins/nic/kvikio_nic_nsys_plugin.cpp:262:66: error: missing initializer for member 'nvtxPayloadSchemaEntry_v1::semantics' [-Werror=missing-field-initializers]
/__w/cudf/cudf/_build/release/_deps/kvikio-src/cpp/nsys_plugins/nic/kvikio_nic_nsys_plugin.cpp:262:66: error: missing initializer for member 'nvtxPayloadSchemaEntry_v1::reserved' [-Werror=missing-field-initializers]
/__w/cudf/cudf/_build/release/_deps/kvikio-src/cpp/nsys_plugins/nic/kvikio_nic_nsys_plugin.cpp:266:66: error: missing initializer for member 'nvtxPayloadSchemaEntry_v1::flags' [-Werror=missing-field-initializers]
  266 |                              .offset      = offsetof(NicRates, tx)},
      |                                                                  ^
/__w/cudf/cudf/_build/release/_deps/kvikio-src/cpp/nsys_plugins/nic/kvikio_nic_nsys_plugin.cpp:266:66: error: missing initializer for member 'nvtxPayloadSchemaEntry_v1::arrayOrUnionDetail' [-Werror=missing-field-initializers]
/__w/cudf/cudf/_build/release/_deps/kvikio-src/cpp/nsys_plugins/nic/kvikio_nic_nsys_plugin.cpp:266:66: error: missing initializer for member 'nvtxPayloadSchemaEntry_v1::semantics' [-Werror=missing-field-initializers]
/__w/cudf/cudf/_build/release/_deps/kvikio-src/cpp/nsys_plugins/nic/kvikio_nic_nsys_plugin.cpp:266:66: error: missing initializer for member 'nvtxPayloadSchemaEntry_v1::reserved' [-Werror=missing-field-initializers]
cc1plus: all warnings being treated as errors
[457/3401] Building CXX object velox/buffer/CMakeFiles/velox.dir/__/common/base/Exceptions.cpp.o
[458/3401] Generating JIT embed for cudf_cuda_embed into /__w/cudf/cudf/_build/release/_deps/cudf-build/rtcx_embed
-- Compressed cudf_cuda_embed's binary from 13452099 bytes to 1134801 bytes (compression ratio: 0.08)
[459/3401] Building CXX object velox/buffer/CMakeFiles/velox.dir/__/common/base/BloomFilter.cpp.o
[460/3401] Building CXX object velox/buffer/CMakeFiles/velox.dir/__/common/base/BitUtil.cpp.o
[461/3401] Building CXX object velox/buffer/CMakeFiles/velox.dir/__/common/base/VeloxException.cpp.o
[462/3401] Building CXX object velox/buffer/CMakeFiles/velox.dir/__/common/base/AdmissionController.cpp.o
[463/3401] Building CXX object velox/buffer/CMakeFiles/velox.dir/__/dwio/common/SortingWriter.cpp.o
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:112: build] Error 1
make[1]: Leaving directory '/__w/cudf/cudf'
make: *** [Makefile:143: cudf] Error 2

```

</details>

Closes #1061

Authors:
  - Matthew Murray (https://github.com/Matt711)

Approvers:
  - Tianyu Liu (https://github.com/kingcrimsontianyu)

URL: https://github.com/rapidsai/kvikio/pull/1068